use std::{collections::HashMap, env, fs, process::Command};

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Space { Scalar(String), Tensor(usize), Qubit(usize), Organoid(usize), Logic(usize), Product(Vec<Space>), Unit }
impl Space {
    fn product(a: Space, b: Space) -> Self { let mut v=match a{Self::Product(v)=>v,x=>vec![x]}; match b{Self::Product(w)=>v.extend(w),x=>v.push(x)}; Self::Product(v) }
    fn parts(&self)->Vec<Space>{match self{Self::Product(v)=>v.clone(),x=>vec![x.clone()]}}
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PrimitiveFamily { Scalar, Tensor, Quantum, Organoid, Logic }
#[derive(Debug, Clone)]
pub struct Primitive { pub name:String, pub domain:Space, pub codomain:Space, pub family:PrimitiveFamily }
#[derive(Debug, Clone)]
pub struct PrimitiveRegistry { pub primitives:HashMap<String,Primitive>, pub spaces:HashMap<String,Space> }
impl PrimitiveRegistry {
    fn new()->Self { let mut r=Self{primitives:HashMap::new(),spaces:HashMap::new()}; r.add("add",Space::Scalar("f64".into()),Space::Scalar("f64".into())); r.add("mul",Space::Scalar("f64".into()),Space::Scalar("f64".into())); r.add("neural_layer",Space::Tensor(128),Space::Tensor(64)); r.add("quantum_gate",Space::Qubit(2),Space::Qubit(2)); r.add("organoid_step",Space::Organoid(64),Space::Organoid(64)); r.add("organoid_pulse",Space::Organoid(64),Space::Organoid(64)); r.add("logic_step",Space::Logic(8),Space::Logic(8)); r }
    fn add(&mut self,n:&str,d:Space,c:Space){let f=family(&d,&c);self.primitives.insert(n.into(),Primitive{name:n.into(),domain:d,codomain:c,family:f});}
    fn declare(&mut self,n:String,d:Space,c:Space)->Result<(),String>{if self.primitives.contains_key(&n){return Err(format!("primitive `{n}` already declared"))}self.add(&n,d,c);Ok(())}
    fn get(&self,n:&str)->Option<&Primitive>{self.primitives.get(n)}
}
fn family(d:&Space,c:&Space)->PrimitiveFamily{match(d,c){(Space::Tensor(_),_)|(_,Space::Tensor(_))=>PrimitiveFamily::Tensor,(Space::Qubit(_),_)|(_,Space::Qubit(_))=>PrimitiveFamily::Quantum,(Space::Organoid(_),_)|(_,Space::Organoid(_))=>PrimitiveFamily::Organoid,(Space::Logic(_),_)|(_,Space::Logic(_))=>PrimitiveFamily::Logic,_=>PrimitiveFamily::Scalar}}

#[derive(Debug, Clone)]
pub enum Flow { Primitive(String), Chain(Box<Flow>,Box<Flow>), Parallel(Box<Flow>,Box<Flow>), Feedback(Box<Flow>), Identity(Space), Derivative(Box<Flow>) }
#[derive(Debug, Clone)]
pub struct FlowDecl { pub name:String, pub domain:Option<Space>, pub codomain:Option<Space>, pub body:Flow }
#[derive(Debug, Clone)]
pub enum TypedFlow { Primitive{ name:String, domain:Space, codomain:Space, family:PrimitiveFamily }, Chain(Box<TypedFlow>,Box<TypedFlow>), Parallel(Box<TypedFlow>,Box<TypedFlow>), Feedback{ inner:Box<TypedFlow>, domain:Space, codomain:Space, trace:Space }, Identity(Space), Derivative{ inner:Box<TypedFlow>, domain:Space, codomain:Space } }
impl TypedFlow { fn ty(&self)->(Space,Space){match self{Self::Primitive{domain,codomain,..}|Self::Feedback{domain,codomain,..}|Self::Derivative{domain,codomain,..} =>(domain.clone(),codomain.clone()),Self::Chain(a,b)=>(a.ty().0,b.ty().1),Self::Parallel(a,b)=>(Space::product(a.ty().0,b.ty().0),Space::product(a.ty().1,b.ty().1)),Self::Identity(s)=>(s.clone(),s.clone())}} }

pub struct Validator<'a>{registry:&'a PrimitiveRegistry, flows:&'a HashMap<String,TypedFlow>}
impl<'a> Validator<'a>{
    fn validate(&self,f:&Flow)->Result<TypedFlow,String>{match f{
        Flow::Primitive(n)=>{if let Some(p)=self.registry.get(n){Ok(TypedFlow::Primitive{name:n.clone(),domain:p.domain.clone(),codomain:p.codomain.clone(),family:p.family.clone()})}else if let Some(t)=self.flows.get(n){Ok(t.clone())}else{Err(format!("undefined primitive or flow `{n}`"))}}
        Flow::Identity(s)=>Ok(TypedFlow::Identity(s.clone())),
        Flow::Chain(a,b)=>{let x=self.validate(a)?;let y=self.validate(b)?;if x.ty().1!=y.ty().0{return Err(format!("chain mismatch: {:?} cannot feed {:?}",x.ty().1,y.ty().0))}Ok(TypedFlow::Chain(Box::new(x),Box::new(y)))},
        Flow::Parallel(a,b)=>{let x=self.validate(a)?;let y=self.validate(b)?;Ok(TypedFlow::Parallel(Box::new(x),Box::new(y)))},
        Flow::Feedback(inner)=>{let t=self.validate(inner)?;let (d,c)=t.ty();let dp=d.parts();let cp=c.parts();if dp.len()<2||cp.len()<2{return Err("feedback requires f : A || U -> B || U".into())}let u=dp.last().unwrap();if u!=cp.last().unwrap(){return Err(format!("feedback trace mismatch: {:?} != {:?}",u,cp.last().unwrap()))}let dd=collapse(Space::Product(dp[..dp.len()-1].to_vec()));let cc=collapse(Space::Product(cp[..cp.len()-1].to_vec()));Ok(TypedFlow::Feedback{inner:Box::new(t),domain:dd,codomain:cc,trace:u.clone()})},
        Flow::Derivative(inner)=>{let t=self.validate(inner)?;let(d,c)=t.ty();Ok(TypedFlow::Derivative{inner:Box::new(t),domain:Space::product(d,c.clone()),codomain:d})}
    }}
}
fn collapse(s:Space)->Space{match s{Space::Product(mut v)if v.len()==1=>v.remove(0),x=>x}}

#[derive(Debug,Clone,PartialEq)]
enum Token{Space,Flow,Grad,Id,Ident(String),Number(usize),Equals,Colon,Arrow,Chain,Parallel,Tilde,LParen,RParen,LAngle,RAngle,Comma,Eof}
struct Lexer<'a>{b:&'a[u8],p:usize}
impl<'a> Lexer<'a>{fn new(s:&'a str)->Self{Self{b:s.as_bytes(),p:0}}fn tokens(&mut self)->Vec<Token>{let mut v=Vec::new();while let Some(t)=self.next(){v.push(t)}v.push(Token::Eof);v}fn next(&mut self)->Option<Token>{while self.p<self.b.len()&&self.b[self.p].is_ascii_whitespace(){self.p+=1}if self.p>=self.b.len(){return None}if self.b[self.p..].starts_with(b"//"){while self.p<self.b.len()&&self.b[self.p]!=b'\n'{self.p+=1}return self.next()}for(o,t)in[(b">>".as_slice(),Token::Chain),(b"||".as_slice(),Token::Parallel),(b"->".as_slice(),Token::Arrow)]{if self.b[self.p..].starts_with(o){self.p+=2;return Some(t)}}let c=self.b[self.p];self.p+=1;Some(match c{b'='=>Token::Equals,b':'=>Token::Colon,b'~'=>Token::Tilde,b'('=>Token::LParen,b')'=>Token::RParen,b'<'=>Token::LAngle,b'>'=>Token::RAngle,b','=>Token::Comma,c if c.is_ascii_digit()=>{let mut n=(c-b'0')as usize;while self.p<self.b.len()&&self.b[self.p].is_ascii_digit(){n=n*10+(self.b[self.p]-b'0')as usize;self.p+=1}Token::Number(n)},c if c.is_ascii_alphabetic()||c==b'_' =>{let s=self.p-1;while self.p<self.b.len()&&(self.b[self.p].is_ascii_alphanumeric()||self.b[self.p]==b'_'){self.p+=1}match std::str::from_utf8(&self.b[s..self.p]).unwrap(){"space"=>Token::Space,"flow"=>Token::Flow,"grad"=>Token::Grad,"id"=>Token::Id,x=>Token::Ident(x.into())}},_=>return self.next()})}}

pub struct Parser{ts:Vec<Token>,p:usize,flows:HashMap<String,Flow>}
impl Parser{fn new(ts:Vec<Token>)->Self{Self{ts,p:0,flows:HashMap::new()}}fn peek(&self)->&Token{&self.ts[self.p]}fn take(&mut self)->Token{let t=self.ts[self.p].clone();if self.p+1<self.ts.len(){self.p+=1}t}fn expect(&mut self,x:Token)->Result<(),String>{let a=self.take();if a==x{Ok(())}else{Err(format!("expected {:?}, got {:?}",x,a))}}fn ident(&mut self)->Result<String,String>{match self.take(){Token::Ident(s)=>Ok(s),x=>Err(format!("expected identifier, got {:?}",x))}}
 fn parse(&mut self,r:&mut PrimitiveRegistry)->Result<Vec<FlowDecl>,String>{let mut out=Vec::new();while*self.peek()!=Token::Eof{match self.peek(){Token::Space=>self.space(r)?,Token::Flow=>{let d=self.flow(r)?;if self.flows.insert(d.name.clone(),d.body.clone()).is_some(){return Err(format!("flow `{}` already declared",d.name))}out.push(d)},Token::Ident(_)=>self.primitive(r)?,x=>return Err(format!("unexpected top-level token {:?}",x))}}Ok(out)}
 fn space(&mut self,r:&mut PrimitiveRegistry)->Result<(),String>{self.take();let n=self.ident()?;self.expect(Token::Equals)?;let s=self.spec(r)?;if r.spaces.insert(n.clone(),s).is_some(){return Err(format!("space `{n}` already declared"))}Ok(())}
 fn primitive(&mut self,r:&mut PrimitiveRegistry)->Result<(),String>{let n=self.ident()?;self.expect(Token::Colon)?;let d=self.spec(r)?;self.expect(Token::Arrow)?;let c=self.spec(r)?;r.declare(n,d,c)}
 fn spec(&mut self,r:&PrimitiveRegistry)->Result<Space,String>{match self.take(){Token::Ident(n)=>{if let Some(s)=r.spaces.get(&n){return Ok(s.clone())}let z=if self.peek()==&Token::LAngle{self.take();let z=match self.take(){Token::Number(n)=>n,x=>return Err(format!("expected dimension, got {:?}",x))};self.expect(Token::RAngle)?;Some(z)}else{None};match(n.as_str(),z){("Tensor"|"Array",Some(n))=>Ok(Space::Tensor(n)),("Qubit"|"Quantum",Some(n))=>Ok(Space::Qubit(n)),("Organoid"|"MEA",Some(n))=>Ok(Space::Organoid(n)),("Logic"|"Bits",Some(n))=>Ok(Space::Logic(n)),(n,None)if["Tensor","Array","Qubit","Quantum","Organoid","MEA","Logic","Bits"].contains(&n)=>Err(format!("space `{n}` requires <dimension>")),(n,Some(_))=>Err(format!("unknown parameterized space `{n}`")),(n,None)=>Err(format!("undeclared space `{n}`"))}},Token::LParen=>{let mut v=vec![self.spec(r)?];while self.peek()==&Token::Parallel{self.take();v.push(self.spec(r)?)}self.expect(Token::RParen)?;if v.len()<2{Err("product requires at least two spaces".into())}else{Ok(Space::Product(v))}},x=>Err(format!("expected space, got {:?}",x))}}
 fn flow(&mut self,r:&PrimitiveRegistry)->Result<FlowDecl,String>{self.take();let n=self.ident()?;let(d,c)=if self.peek()==&Token::Colon{self.take();let d=self.spec(r)?;self.expect(Token::Arrow)?;let c=self.spec(r)?;(Some(d),Some(c))}else{(None,None)};self.expect(Token::Equals)?;Ok(FlowDecl{name:n,domain:d,codomain:c,body:self.expr(r)?})}
 fn expr(&mut self,r:&PrimitiveRegistry)->Result<Flow,String>{let mut x=self.parallel(r)?;while self.peek()==&Token::Chain{self.take();x=Flow::Chain(Box::new(x),Box::new(self.parallel(r)?))}Ok(x)}fn parallel(&mut self,r:&PrimitiveRegistry)->Result<Flow,String>{let mut x=self.primary(r)?;while self.peek()==&Token::Parallel{self.take();x=Flow::Parallel(Box::new(x),Box::new(self.primary(r)?))}Ok(x)}fn primary(&mut self,r:&PrimitiveRegistry)->Result<Flow,String>{match self.take(){Token::Tilde=>Ok(Flow::Feedback(Box::new(self.primary(r)?))),Token::Grad=>{self.expect(Token::LParen)?;let x=self.expr(r)?;self.expect(Token::RParen)?;Ok(Flow::Derivative(Box::new(x)))},Token::Id=>{if self.peek()==&Token::LParen{self.take();let s=self.spec(r)?;self.expect(Token::RParen)?;Ok(Flow::Identity(s))}else{Ok(Flow::Identity(Space::Unit))}},Token::Ident(n)=>Ok(self.flows.get(&n).cloned().unwrap_or(Flow::Primitive(n))),Token::LParen=>{let x=self.expr(r)?;self.expect(Token::RParen)?;Ok(x)},x=>Err(format!("unexpected flow token {:?}",x))}}}

struct Emitter<'a>{r:&'a PrimitiveRegistry}
impl<'a> Emitter<'a>{fn emit(&self,d:&[FlowDecl])->String{let mut c=String::from("#include <stdint.h>\n#include <stddef.h>\n#include <stdio.h>\n#include <string.h>\ntypedef struct { int qasm_fd; int mea_fd; } IntelligenceDevices;\nstatic void tensor_forward(const float*i,float*o,size_t n,size_t m){for(size_t x=0;x<m;x++){o[x]=0;for(size_t y=0;y<n;y++)o[x]+=i[y]*.01f;}}\nstatic void tensor_reverse(const float*o,float*i,size_t n,size_t m){for(size_t x=0;x<n;x++){i[x]=0;for(size_t y=0;y<m;y++)i[x]+=o[y]*.01f;}}\nstatic void quantum_forward(IntelligenceDevices*d,const float*i,float*o,size_t q){(void)d;memcpy(o,i,(1u<<q)*2*sizeof(float));}\nstatic void quantum_reverse(IntelligenceDevices*d,const float*o,float*i,size_t q){(void)d;memcpy(i,o,(1u<<q)*2*sizeof(float));}\nstatic void organoid_forward(IntelligenceDevices*d,const float*i,float*o,size_t n){(void)d;memcpy(o,i,n*sizeof(float));}\nstatic void organoid_reverse(IntelligenceDevices*d,const float*o,float*i,size_t n){(void)d;memcpy(i,o,n*sizeof(float));}\nstatic void logic_forward(const uint8_t*i,uint8_t*o,size_t n){memcpy(o,i,(n+7)/8);}\nstatic void logic_reverse(const uint8_t*o,uint8_t*i,size_t n){memcpy(i,o,(n+7)/8);}\n\n");for x in d{c.push_str(&format!("/* typed flow {} */\n",x.name));self.emit_flow(&x.body,&mut c,false)}c.push_str("int main(void){puts(\"Intelligence categorical runtime ready\");return 0;}\n");c}fn emit_flow(&self,f:&Flow,c:&mut String,rev:bool){match f{Flow::Primitive(n)=>if let Some(p)=self.r.get(n){c.push_str(&format!("/* emit {:?} primitive {} ({}) */\n",p.family,n,if rev{"reverse"}else{"forward"}))},Flow::Chain(a,b)|Flow::Parallel(a,b)=>{self.emit_flow(a,c,rev);self.emit_flow(b,c,rev)},Flow::Feedback(x)=>self.emit_flow(x,c,rev),Flow::Identity(_)=>{},Flow::Derivative(x)=>self.emit_flow(x,c,true)}}}

fn main(){let path=env::args().nth(1).unwrap_or_else(||"program.cat".into());let source=match fs::read_to_string(&path){Ok(x)=>x,Err(e)=>{eprintln!("read error: {e}");return}};let mut r=PrimitiveRegistry::new();let mut l=Lexer::new(&source);let mut p=Parser::new(l.tokens());let decls=match p.parse(&mut r){Ok(x)=>x,Err(e)=>{eprintln!("parse error: {e}");return}};let mut typed=HashMap::new();for d in &decls{let v=Validator{registry:&r,flows:&typed};let t=match v.validate(&d.body){Ok(x)=>x,Err(e)=>{eprintln!("type error in {}: {e}",d.name);return}};let ty=t.ty();if let(Some(a),Some(b))=(&d.domain,&d.codomain){if ty!=(a.clone(),b.clone()){eprintln!("annotation mismatch in {}",d.name);return}}typed.insert(d.name.clone(),t);}let out=Emitter{r:&r}.emit(&decls);if let Err(e)=fs::write("payload.c",out){eprintln!("write error: {e}");return}match Command::new("clang").args(["-std=c99","-O2","payload.c","-o","binary_app"]).status(){Ok(s)if s.success()=>println!("Compiled successfully: binary_app"),Ok(_)=>eprintln!("C compilation failed; payload.c preserved"),Err(e)=>eprintln!("clang error: {e}; payload.c preserved")}}
